### ISSUE TITLE
After respecing from fighter to wizard and choosing Greenmage on 2nd level, i can't get any spells anymore

### ISSUE THREAD

**Issue by AgainPsychoX** [SolastaMods/SolastaRespec#1]
After respecing from fighter to wizard and choosing Greenmage on 2nd level, i can't get any spells anymore. Leveling down and up does help either. 

Also, while levelling down the spells from first wizard level seem to disappear (only cantrips left).

**Comment by ThyWoof** [comment]
Fixed on V0.1.2.

**Comment by AgainPsychoX** [comment]
Thank you, it works now :)
